-- ============================================================================
-- MySQL Protocol Parser Validation Test SQL
-- ============================================================================
-- This file contains SQL statements and commands to test MySQL protocol parser
-- implementations. To capture protocol traffic, use tools like:
--   - tcpdump -i lo -w mysql.pcap port 3306
--   - Wireshark with MySQL protocol dissector
--   - mysql client with --debug option
--
-- Usage:
--   1. Start packet capture: tcpdump -i any -w mysql.pcap port 3306
--   2. Connect to MySQL and execute these statements
--   3. Analyze captured packets with your protocol parser
-- ============================================================================

-- Note: Use mysql client to generate protocol traffic
-- mysql -h 127.0.0.1 -P 3306 -u root -p

-- ============================================================================
-- Test 1: COM_QUIT (0x01)
-- ============================================================================
-- Connect and immediately quit
-- mysql -h 127.0.0.1 -u root -p -e "SELECT 1"
-- The connection close generates COM_QUIT

-- ============================================================================
-- Test 2: COM_INIT_DB (0x02)
-- ============================================================================
-- Change database
USE mysql;
USE information_schema;
USE sys;

-- ============================================================================
-- Test 3: COM_QUERY (0x03) - Most Common Command
-- ============================================================================

-- Simple SELECT
SELECT 1;
SELECT 1, 2, 3;
SELECT 'Hello', 'World';
SELECT NOW();

-- SELECT with WHERE
SELECT * FROM mysql.user LIMIT 1;
SELECT User, Host FROM mysql.user WHERE User != '';

-- JOIN query
SELECT 
    t.TABLE_SCHEMA,
    t.TABLE_NAME,
    c.COLUMN_NAME
FROM information_schema.TABLES t
JOIN information_schema.COLUMNS c 
    ON t.TABLE_SCHEMA = c.TABLE_SCHEMA 
    AND t.TABLE_NAME = c.TABLE_NAME
WHERE t.TABLE_SCHEMA = 'mysql'
LIMIT 5;

-- Aggregation
SELECT COUNT(*) FROM mysql.user;
SELECT TABLE_SCHEMA, COUNT(*) as table_count
FROM information_schema.TABLES
GROUP BY TABLE_SCHEMA;

-- INSERT
CREATE DATABASE IF NOT EXISTS protocol_test;
USE protocol_test;

CREATE TABLE test_table (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    value INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO test_table (name, value) VALUES ('test1', 100);
INSERT INTO test_table (name, value) VALUES ('test2', 200), ('test3', 300);

-- UPDATE
UPDATE test_table SET value = value + 10 WHERE id = 1;

-- DELETE
DELETE FROM test_table WHERE id = 3;

-- DDL statements
CREATE TABLE test_table2 (id INT, data VARCHAR(50));
ALTER TABLE test_table2 ADD COLUMN created_at TIMESTAMP;
DROP TABLE test_table2;

-- Transaction
START TRANSACTION;
INSERT INTO test_table (name, value) VALUES ('tx1', 1000);
UPDATE test_table SET value = 1100 WHERE name = 'tx1';
COMMIT;

START TRANSACTION;
INSERT INTO test_table (name, value) VALUES ('tx2', 2000);
ROLLBACK;

-- ============================================================================
-- Test 4: COM_FIELD_LIST (0x04) - Deprecated
-- ============================================================================
-- This command is deprecated and typically not used by modern clients
-- It was used by older mysql clients with "SHOW COLUMNS" equivalent

-- Modern equivalent:
SHOW COLUMNS FROM test_table;
DESCRIBE test_table;

-- ============================================================================
-- Test 5: COM_STATISTICS (0x09)
-- ============================================================================
-- Generated by: mysql -h 127.0.0.1 -u root -p -e "status"
-- Or within mysql client: \s or status

-- From SQL, you can get similar info:
SHOW STATUS;
SHOW STATUS LIKE 'Uptime%';
SHOW STATUS LIKE 'Questions';
SHOW STATUS LIKE 'Threads%';

-- ============================================================================
-- Test 6: COM_DEBUG (0x0D)
-- ============================================================================
-- Requires SUPER privilege
-- Generated by: mysqladmin -u root -p debug
-- Or: mysql client: \T (debug dump)

-- Note: This requires SUPER privilege and is rarely used

-- ============================================================================
-- Test 7: COM_PING (0x0E)
-- ============================================================================
-- Generated by: mysqladmin -u root -p ping
-- Or periodically by connection pools

-- From SQL (alternative):
SELECT 1;  -- Often used as ping replacement

-- ============================================================================
-- Test 8: COM_CHANGE_USER (0x11)
-- ============================================================================
-- Generated by mysql_change_user() C API function
-- Not directly available via SQL

-- Note: You can observe this by using mysql client with --user option multiple times
-- mysql -u root -p
-- Then: system mysql -u root -e "SELECT USER()"

-- ============================================================================
-- Test 9: COM_RESET_CONNECTION (0x1F)
-- ============================================================================
-- Resets connection state without reconnecting
-- Generated by: mysql_reset_connection() C API function

-- Effects: clears session variables, temp tables, prepared statements
-- Alternative from SQL:
RESET QUERY CACHE;  -- Note: Different from COM_RESET_CONNECTION

-- ============================================================================
-- Test 10: COM_STMT_PREPARE (0x16) - Prepared Statements
-- ============================================================================
-- Binary protocol - requires C API or connector that supports it

-- Via mysql client (limited support):
PREPARE stmt1 FROM 'SELECT * FROM test_table WHERE id = ?';
SET @id = 1;
EXECUTE stmt1 USING @id;
DEALLOCATE PREPARE stmt1;

-- More complex prepared statement
PREPARE stmt2 FROM 'INSERT INTO test_table (name, value) VALUES (?, ?)';
SET @name = 'prepared_test';
SET @value = 999;
EXECUTE stmt2 USING @name, @value;
DEALLOCATE PREPARE stmt2;

-- Prepared statement with multiple parameters
PREPARE stmt3 FROM 'UPDATE test_table SET value = ? WHERE name = ? AND value > ?';
SET @new_value = 1500;
SET @name_filter = 'test1';
SET @min_value = 0;
EXECUTE stmt3 USING @new_value, @name_filter, @min_value;
DEALLOCATE PREPARE stmt3;

-- ============================================================================
-- Test 11: COM_SET_OPTION (0x1B)
-- ============================================================================
-- Enable/disable multi-statement support

-- Enable multi-statements (via client):
-- mysql_set_server_option(MYSQL_OPTION_MULTI_STATEMENTS_ON)

-- Multi-statement queries (if enabled):
-- SELECT 1; SELECT 2; SELECT 3;

-- Disable multi-statements:
-- mysql_set_server_option(MYSQL_OPTION_MULTI_STATEMENTS_OFF)

-- ============================================================================
-- Test 12: Resultset Variations
-- ============================================================================

-- Empty resultset
SELECT * FROM test_table WHERE id = 999999;

-- Large resultset
SELECT * FROM test_table;

-- Multiple columns with different types
SELECT 
    1 AS tiny_int,
    32767 AS small_int,
    2147483647 AS int_val,
    9223372036854775807 AS big_int,
    3.14159 AS float_val,
    2.718281828459045 AS double_val,
    'string' AS varchar_val,
    NOW() AS datetime_val,
    CURRENT_DATE AS date_val,
    CURRENT_TIME AS time_val,
    NULL AS null_val,
    X'48656C6C6F' AS binary_val;

-- All MySQL data types in resultset
CREATE TABLE test_all_types (
    col_tinyint TINYINT,
    col_smallint SMALLINT,
    col_mediumint MEDIUMINT,
    col_int INT,
    col_bigint BIGINT,
    col_decimal DECIMAL(10,2),
    col_float FLOAT,
    col_double DOUBLE,
    col_date DATE,
    col_time TIME,
    col_datetime DATETIME,
    col_timestamp TIMESTAMP,
    col_year YEAR,
    col_char CHAR(10),
    col_varchar VARCHAR(255),
    col_text TEXT,
    col_blob BLOB,
    col_enum ENUM('A','B','C'),
    col_set SET('X','Y','Z'),
    col_json JSON
);

INSERT INTO test_all_types VALUES (
    127, 32767, 8388607, 2147483647, 9223372036854775807,
    12345.67, 3.14, 2.718,
    '2025-01-15', '14:30:00', '2025-01-15 14:30:00', 
    '2025-01-15 14:30:00', 2025,
    'char', 'varchar', 'text data', 'blob data',
    'B', 'X,Y', '{"key": "value"}'
);

SELECT * FROM test_all_types;

-- ============================================================================
-- Test 13: NULL Values in Results
-- ============================================================================

CREATE TABLE test_nulls (
    id INT PRIMARY KEY,
    nullable_int INT,
    nullable_varchar VARCHAR(100),
    nullable_text TEXT,
    nullable_date DATE
);

INSERT INTO test_nulls VALUES (1, NULL, 'not null', 'text', '2025-01-01');
INSERT INTO test_nulls VALUES (2, 100, NULL, 'text2', NULL);
INSERT INTO test_nulls VALUES (3, NULL, NULL, NULL, NULL);

SELECT * FROM test_nulls;

-- ============================================================================
-- Test 14: Large Resultsets (Multi-Packet)
-- ============================================================================

-- Create table with enough data to span multiple packets
CREATE TABLE test_large_result (
    id INT PRIMARY KEY AUTO_INCREMENT,
    data VARCHAR(1000)
);

INSERT INTO test_large_result (data)
SELECT REPEAT('LargeData', 100) FROM
    (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t1
CROSS JOIN
    (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t2
CROSS JOIN
    (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t3;

SELECT * FROM test_large_result;

-- ============================================================================
-- Test 15: Warnings and Info Messages
-- ============================================================================

-- Generate warnings
SELECT 1/0;  -- Division by zero warning

CREATE TABLE test_warnings (
    id INT,
    value INT
);

INSERT INTO test_warnings VALUES (1, 100);
INSERT INTO test_warnings VALUES (1, 200);  -- No warning (no unique constraint)

-- Drop non-existent table (generates warning in some cases)
-- DROP TABLE IF EXISTS non_existent_table;

SHOW WARNINGS;

-- ============================================================================
-- Test 16: Error Responses
-- ============================================================================

-- Syntax error
-- SELECT * FORM test_table;  -- Uncomment to test

-- Table doesn't exist
-- SELECT * FROM non_existent_table;  -- Uncomment to test

-- Column doesn't exist
-- SELECT non_existent_column FROM test_table;  -- Uncomment to test

-- Duplicate entry error
CREATE TABLE test_errors (
    id INT PRIMARY KEY,
    data VARCHAR(50)
);

INSERT INTO test_errors VALUES (1, 'data1');
-- INSERT INTO test_errors VALUES (1, 'duplicate');  -- Uncomment to test

-- ============================================================================
-- Test 17: SHOW Commands (Various Protocol Responses)
-- ============================================================================

SHOW DATABASES;
SHOW TABLES;
SHOW TABLES FROM mysql;
SHOW COLUMNS FROM test_table;
SHOW INDEX FROM test_table;
SHOW CREATE TABLE test_table;
SHOW VARIABLES LIKE 'version%';
SHOW STATUS LIKE 'Threads%';
SHOW PROCESSLIST;
SHOW GRANTS;
SHOW MASTER STATUS;
SHOW REPLICA STATUS;

-- ============================================================================
-- Test 18: Information Schema Queries
-- ============================================================================

SELECT * FROM information_schema.SCHEMATA;
SELECT * FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'protocol_test';
SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'protocol_test' AND TABLE_NAME = 'test_table';
SELECT * FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = 'protocol_test';

-- ============================================================================
-- Test 19: Stored Procedures (COM_QUERY with CALL)
-- ============================================================================

DELIMITER //
CREATE PROCEDURE test_proc(IN p_id INT, OUT p_count INT)
BEGIN
    SELECT COUNT(*) INTO p_count FROM test_table WHERE id > p_id;
    SELECT * FROM test_table WHERE id > p_id;
END //
DELIMITER ;

SET @count = 0;
CALL test_proc(0, @count);
SELECT @count;

DROP PROCEDURE test_proc;

-- ============================================================================
-- Test 20: User Variables
-- ============================================================================

SET @var1 = 100;
SET @var2 = 'string value';
SET @var3 = NOW();

SELECT @var1, @var2, @var3;

SELECT @result := COUNT(*) FROM test_table;
SELECT @result;

-- ============================================================================
-- Test 21: Session Variables
-- ============================================================================

SHOW VARIABLES LIKE 'sql_mode';
SET SESSION sql_mode = 'TRADITIONAL';
SHOW VARIABLES LIKE 'sql_mode';
SET SESSION sql_mode = DEFAULT;

SHOW VARIABLES LIKE 'autocommit';
SET autocommit = 0;
SHOW VARIABLES LIKE 'autocommit';
SET autocommit = 1;

-- ============================================================================
-- Test 22: Character Set and Collation
-- ============================================================================

SHOW CHARACTER SET;
SHOW COLLATION;

SET NAMES utf8mb4;
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE test_charset (
    id INT PRIMARY KEY,
    data_utf8 VARCHAR(100) CHARACTER SET utf8mb4,
    data_latin1 VARCHAR(100) CHARACTER SET latin1
);

INSERT INTO test_charset VALUES (1, 'UTF8: 你好', 'Latin1: Hello');
SELECT * FROM test_charset;

DROP TABLE test_charset;

-- ============================================================================
-- Test 23: Complex Queries
-- ============================================================================

-- Subquery
SELECT * FROM test_table WHERE value > (SELECT AVG(value) FROM test_table);

-- UNION
SELECT 'Table1' AS source, id, name FROM test_table WHERE id < 5
UNION ALL
SELECT 'Table1_High' AS source, id, name FROM test_table WHERE id >= 5;

-- Common Table Expression (CTE)
WITH cte AS (
    SELECT id, name, value,
           ROW_NUMBER() OVER (ORDER BY value DESC) AS rn
    FROM test_table
)
SELECT * FROM cte WHERE rn <= 3;

-- Window function
SELECT 
    id, name, value,
    AVG(value) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS moving_avg
FROM test_table;

-- ============================================================================
-- Test 24: Batch Operations
-- ============================================================================

-- Multi-row insert
INSERT INTO test_table (name, value) VALUES
    ('batch1', 1000),
    ('batch2', 2000),
    ('batch3', 3000),
    ('batch4', 4000),
    ('batch5', 5000);

-- Update with CASE
UPDATE test_table 
SET value = CASE 
    WHEN id % 2 = 0 THEN value * 2
    WHEN id % 3 = 0 THEN value * 3
    ELSE value
END;

-- ============================================================================
-- Cleanup
-- ============================================================================

DROP TABLE IF EXISTS test_table;
DROP TABLE IF EXISTS test_all_types;
DROP TABLE IF EXISTS test_nulls;
DROP TABLE IF EXISTS test_large_result;
DROP TABLE IF EXISTS test_warnings;
DROP TABLE IF EXISTS test_errors;

DROP DATABASE IF EXISTS protocol_test;

-- ============================================================================
-- Summary
-- ============================================================================

SELECT 'Protocol validation tests completed!' AS Status;
SELECT 'Analyze captured packets with your protocol parser' AS NextStep;
SELECT 'Look for various COM_* commands and response packet types' AS Info;

-- Note: To capture MySQL protocol traffic:
-- 1. tcpdump -i any -w mysql_traffic.pcap -s 65535 port 3306
-- 2. Run these SQL statements
-- 3. Stop tcpdump (Ctrl+C)
-- 4. Analyze with: tcpdump -r mysql_traffic.pcap -X
--    Or use Wireshark with MySQL protocol dissector

-- To test specific protocol features:
-- - Compression: Connect with --compress flag
-- - SSL: Connect with --ssl-mode=REQUIRED
-- - Prepared statements: Use programming language with prepared statement support
