-- ============================================================================
-- InnoDB Redo Log Parser Validation Test SQL
-- ============================================================================
-- This file contains SQL statements to generate various types of redo log
-- records for testing and validating redo log parser implementations.
--
-- Usage:
--   1. Ensure InnoDB is enabled (default)
--   2. Execute these statements in order
--   3. Examine redo log files (ib_logfile* or #innodb_redo/)
--   4. Parse the redo logs to verify your parser
-- ============================================================================

-- Setup
DROP DATABASE IF EXISTS redo_test;
CREATE DATABASE redo_test;
USE redo_test;

-- ============================================================================
-- Test 1: MLOG_1BYTE, MLOG_2BYTES, MLOG_4BYTES, MLOG_8BYTES
-- ============================================================================
-- Generated by various internal operations and metadata updates

CREATE TABLE test_basic_writes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    data1 TINYINT,
    data2 SMALLINT,
    data4 INT,
    data8 BIGINT
) ENGINE=InnoDB;

INSERT INTO test_basic_writes (data1, data2, data4, data8) VALUES
    (127, 32767, 2147483647, 9223372036854775807);

UPDATE test_basic_writes SET data1 = 100 WHERE id = 1;

-- ============================================================================
-- Test 2: MLOG_REC_INSERT (Record Insert)
-- ============================================================================

CREATE TABLE test_rec_insert (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    value DECIMAL(10,2)
) ENGINE=InnoDB;

-- Simple insert
START TRANSACTION;
INSERT INTO test_rec_insert VALUES (1, 'Alice', 100.50);
COMMIT;

-- Multiple inserts in one transaction
START TRANSACTION;
INSERT INTO test_rec_insert VALUES (2, 'Bob', 200.75);
INSERT INTO test_rec_insert VALUES (3, 'Charlie', 300.25);
INSERT INTO test_rec_insert VALUES (4, 'David', 400.00);
COMMIT;

-- ============================================================================
-- Test 3: MLOG_REC_UPDATE_IN_PLACE (Update in Place)
-- ============================================================================

-- Update that doesn't change record size
START TRANSACTION;
UPDATE test_rec_insert SET value = 150.75 WHERE id = 1;
COMMIT;

START TRANSACTION;
UPDATE test_rec_insert SET name = 'Alice2' WHERE id = 1;
COMMIT;

-- ============================================================================
-- Test 4: MLOG_REC_DELETE (Record Delete)
-- ============================================================================

START TRANSACTION;
DELETE FROM test_rec_insert WHERE id = 4;
COMMIT;

-- ============================================================================
-- Test 5: MLOG_REC_CLUST_DELETE_MARK (Mark Deleted)
-- ============================================================================
-- InnoDB marks records as deleted before purging them

CREATE TABLE test_delete_mark (
    id INT PRIMARY KEY,
    data VARCHAR(50)
) ENGINE=InnoDB;

START TRANSACTION;
INSERT INTO test_delete_mark VALUES (1, 'test1');
INSERT INTO test_delete_mark VALUES (2, 'test2');
COMMIT;

START TRANSACTION;
DELETE FROM test_delete_mark WHERE id = 1;
COMMIT;

-- The record is first marked deleted, then later purged

-- ============================================================================
-- Test 6: MLOG_REC_SEC_DELETE_MARK (Secondary Index Delete Mark)
-- ============================================================================

CREATE TABLE test_sec_index (
    id INT PRIMARY KEY,
    email VARCHAR(100),
    name VARCHAR(100),
    INDEX idx_email (email),
    INDEX idx_name (name)
) ENGINE=InnoDB;

START TRANSACTION;
INSERT INTO test_sec_index VALUES (1, 'alice@example.com', 'Alice');
INSERT INTO test_sec_index VALUES (2, 'bob@example.com', 'Bob');
COMMIT;

-- Deleting generates delete marks for secondary indexes
START TRANSACTION;
DELETE FROM test_sec_index WHERE id = 1;
COMMIT;

-- ============================================================================
-- Test 7: MLOG_PAGE_CREATE (Create Index Page)
-- ============================================================================
-- Generated when creating new B-tree pages

CREATE TABLE test_page_create (
    id INT PRIMARY KEY,
    data VARCHAR(1000)
) ENGINE=InnoDB;

-- Insert enough data to cause page splits
START TRANSACTION;
INSERT INTO test_page_create
SELECT i, REPEAT('X', 900)
FROM (SELECT 1 AS i UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
      UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t;
COMMIT;

-- ============================================================================
-- Test 8: MLOG_COMP_PAGE_CREATE (Compact Page Create)
-- ============================================================================
-- ROW_FORMAT=COMPACT generates MLOG_COMP_PAGE_CREATE

CREATE TABLE test_compact_page (
    id INT PRIMARY KEY,
    data TEXT
) ENGINE=InnoDB ROW_FORMAT=COMPACT;

START TRANSACTION;
INSERT INTO test_compact_page SELECT i, REPEAT('Data', 250) FROM
(SELECT 1 AS i UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t;
COMMIT;

-- ============================================================================
-- Test 9: MLOG_PAGE_REORGANIZE (Page Reorganization)
-- ============================================================================
-- Generated when page is reorganized to reclaim space

CREATE TABLE test_reorganize (
    id INT PRIMARY KEY,
    data VARCHAR(500)
) ENGINE=InnoDB;

-- Fill page
START TRANSACTION;
INSERT INTO test_reorganize SELECT i, REPEAT('A', 400) FROM
(SELECT 1 AS i UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t;
COMMIT;

-- Delete some records to fragment the page
START TRANSACTION;
DELETE FROM test_reorganize WHERE id IN (2, 4, 6, 8);
COMMIT;

-- Update to trigger reorganization
START TRANSACTION;
UPDATE test_reorganize SET data = REPEAT('B', 400) WHERE id = 1;
COMMIT;

-- ============================================================================
-- Test 10: MLOG_UNDO_INSERT, MLOG_UNDO_HDR_CREATE (Undo Log)
-- ============================================================================
-- Generated automatically for all DML operations

CREATE TABLE test_undo (
    id INT PRIMARY KEY,
    data VARCHAR(100)
) ENGINE=InnoDB;

-- Each transaction creates undo records
START TRANSACTION;
INSERT INTO test_undo VALUES (1, 'data1');
INSERT INTO test_undo VALUES (2, 'data2');
COMMIT;

START TRANSACTION;
UPDATE test_undo SET data = 'updated' WHERE id = 1;
COMMIT;

START TRANSACTION;
DELETE FROM test_undo WHERE id = 2;
COMMIT;

-- ============================================================================
-- Test 11: MLOG_WRITE_STRING (Write String to Page)
-- ============================================================================
-- Generated for various metadata and special data writes

CREATE TABLE test_write_string (
    id INT PRIMARY KEY,
    description TEXT
) ENGINE=InnoDB;

START TRANSACTION;
INSERT INTO test_write_string VALUES (1, REPEAT('LongTextString', 100));
COMMIT;

-- ============================================================================
-- Test 12: MLOG_FILE_CREATE (File Creation)
-- ============================================================================
-- Generated when creating new tablespace files

-- Create file-per-table tablespace
CREATE TABLE test_file_create (
    id INT PRIMARY KEY,
    data VARCHAR(100)
) ENGINE=InnoDB DATA DIRECTORY = '';

-- ============================================================================
-- Test 13: MLOG_FILE_RENAME (File Rename)
-- ============================================================================

CREATE TABLE test_rename_old (
    id INT PRIMARY KEY
) ENGINE=InnoDB;

-- Rename table (generates file rename records)
RENAME TABLE test_rename_old TO test_rename_new;

-- ============================================================================
-- Test 14: MLOG_FILE_DELETE (File Delete)
-- ============================================================================

CREATE TABLE test_file_delete (
    id INT PRIMARY KEY
) ENGINE=InnoDB;

-- Drop table (generates file delete records)
DROP TABLE test_file_delete;

-- ============================================================================
-- Test 15: MLOG_FILE_EXTEND (File Extension)
-- ============================================================================
-- Generated when tablespace grows

CREATE TABLE test_file_extend (
    id INT PRIMARY KEY AUTO_INCREMENT,
    data LONGTEXT
) ENGINE=InnoDB;

-- Insert large amount of data to extend tablespace
START TRANSACTION;
INSERT INTO test_file_extend (data)
SELECT REPEAT('X', 10000) FROM
(SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t1
CROSS JOIN
(SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) t2;
COMMIT;

-- ============================================================================
-- Test 16: MLOG_ZIP_* (Compressed Page Operations)
-- ============================================================================
-- ROW_FORMAT=COMPRESSED generates MLOG_ZIP_* records

CREATE TABLE test_compressed (
    id INT PRIMARY KEY,
    data1 TEXT,
    data2 TEXT,
    data3 TEXT
) ENGINE=InnoDB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

START TRANSACTION;
INSERT INTO test_compressed VALUES (1, REPEAT('A', 5000), REPEAT('B', 5000), REPEAT('C', 5000));
INSERT INTO test_compressed VALUES (2, REPEAT('D', 5000), REPEAT('E', 5000), REPEAT('F', 5000));
COMMIT;

START TRANSACTION;
UPDATE test_compressed SET data1 = REPEAT('X', 5000) WHERE id = 1;
COMMIT;

-- ============================================================================
-- Test 17: MLOG_PAGE_CREATE_RTREE (R-Tree Creation)
-- ============================================================================
-- Generated for spatial indexes

CREATE TABLE test_spatial (
    id INT PRIMARY KEY AUTO_INCREMENT,
    location POINT NOT NULL,
    SPATIAL INDEX idx_location (location)
) ENGINE=InnoDB;

START TRANSACTION;
INSERT INTO test_spatial (location) VALUES
    (ST_GeomFromText('POINT(0 0)')),
    (ST_GeomFromText('POINT(1 1)')),
    (ST_GeomFromText('POINT(2 2)')),
    (ST_GeomFromText('POINT(3 3)')),
    (ST_GeomFromText('POINT(10 10)'));
COMMIT;

-- ============================================================================
-- Test 18: MLOG_INDEX_LOAD (Index Loading)
-- ============================================================================
-- Generated during fast index creation (ALTER TABLE ... ADD INDEX)

CREATE TABLE test_index_load (
    id INT PRIMARY KEY,
    col1 VARCHAR(100),
    col2 VARCHAR(100),
    col3 VARCHAR(100)
) ENGINE=InnoDB;

-- Insert data first
START TRANSACTION;
INSERT INTO test_index_load
SELECT i, CONCAT('col1_', i), CONCAT('col2_', i), CONCAT('col3_', i)
FROM (SELECT 1 AS i UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
      UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
      UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15) t;
COMMIT;

-- Add index using fast creation (generates MLOG_INDEX_LOAD)
ALTER TABLE test_index_load ADD INDEX idx_col1 (col1), ALGORITHM=INPLACE;
ALTER TABLE test_index_load ADD INDEX idx_col2 (col2), ALGORITHM=INPLACE;

-- ============================================================================
-- Test 19: MLOG_TABLE_DYNAMIC_META (Dynamic Metadata)
-- ============================================================================
-- Generated when updating persistent dynamic metadata

-- AUTO_INCREMENT changes
CREATE TABLE test_dynamic_meta (
    id INT PRIMARY KEY AUTO_INCREMENT,
    data VARCHAR(50)
) ENGINE=InnoDB AUTO_INCREMENT=1000;

START TRANSACTION;
INSERT INTO test_dynamic_meta (data) VALUES ('test1');
COMMIT;

-- Explicit AUTO_INCREMENT modification
ALTER TABLE test_dynamic_meta AUTO_INCREMENT=2000;

-- ============================================================================
-- Test 20: Complex Multi-Table Transactions
-- ============================================================================

CREATE TABLE test_orders (
    order_id INT PRIMARY KEY AUTO_INCREMENT,
    customer VARCHAR(100),
    total DECIMAL(10,2)
) ENGINE=InnoDB;

CREATE TABLE test_order_items (
    item_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    product VARCHAR(100),
    price DECIMAL(10,2),
    FOREIGN KEY (order_id) REFERENCES test_orders(order_id)
) ENGINE=InnoDB;

-- Multi-record transaction (generates MLOG_MULTI_REC_END)
START TRANSACTION;
INSERT INTO test_orders (customer, total) VALUES ('John Doe', 0);
SET @order_id = LAST_INSERT_ID();
INSERT INTO test_order_items (order_id, product, price) VALUES (@order_id, 'Item1', 10.00);
INSERT INTO test_order_items (order_id, product, price) VALUES (@order_id, 'Item2', 20.00);
INSERT INTO test_order_items (order_id, product, price) VALUES (@order_id, 'Item3', 30.00);
UPDATE test_orders SET total = 60.00 WHERE order_id = @order_id;
COMMIT;

-- ============================================================================
-- Test 21: BLOB/TEXT Operations
-- ============================================================================

CREATE TABLE test_blob (
    id INT PRIMARY KEY,
    small_text TEXT,
    medium_text MEDIUMTEXT,
    long_text LONGTEXT,
    blob_data BLOB
) ENGINE=InnoDB;

START TRANSACTION;
INSERT INTO test_blob VALUES (
    1,
    REPEAT('Small text data. ', 100),
    REPEAT('Medium text data. ', 1000),
    REPEAT('Long text data with many characters. ', 5000),
    REPEAT(CHAR(65), 10000)  -- Binary data
);
COMMIT;

-- Update BLOB (may generate MLOG_ZIP_WRITE_BLOB_PTR for externally stored)
START TRANSACTION;
UPDATE test_blob SET long_text = REPEAT('Updated long text. ', 5000) WHERE id = 1;
COMMIT;

-- ============================================================================
-- Test 22: All Data Types
-- ============================================================================

CREATE TABLE test_all_datatypes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    -- Integer types
    tiny TINYINT,
    small SMALLINT,
    medium MEDIUMINT,
    normal INT,
    big BIGINT,
    -- Floating point
    float_col FLOAT,
    double_col DOUBLE,
    decimal_col DECIMAL(10,2),
    -- Date/Time
    date_col DATE,
    time_col TIME,
    datetime_col DATETIME,
    timestamp_col TIMESTAMP,
    year_col YEAR,
    -- String
    char_col CHAR(50),
    varchar_col VARCHAR(255),
    text_col TEXT,
    -- Binary
    binary_col BINARY(20),
    varbinary_col VARBINARY(255),
    blob_col BLOB,
    -- Special
    enum_col ENUM('A', 'B', 'C'),
    set_col SET('X', 'Y', 'Z'),
    json_col JSON
) ENGINE=InnoDB;

START TRANSACTION;
INSERT INTO test_all_datatypes (
    tiny, small, medium, normal, big,
    float_col, double_col, decimal_col,
    date_col, time_col, datetime_col, timestamp_col, year_col,
    char_col, varchar_col, text_col,
    binary_col, varbinary_col, blob_col,
    enum_col, set_col, json_col
) VALUES (
    127, 32767, 8388607, 2147483647, 9223372036854775807,
    3.14, 2.718281828, 12345.67,
    '2025-01-15', '14:30:00', '2025-01-15 14:30:00', '2025-01-15 14:30:00', 2025,
    'char data', 'varchar data', 'text data',
    'binary', 'varbinary', 'blob data',
    'B', 'X,Y', '{"key": "value", "num": 123}'
);
COMMIT;

-- ============================================================================
-- Test 23: Trigger Checkpoint
-- ============================================================================
-- Force a checkpoint to see checkpoint-related records

-- Generate significant redo log activity
CREATE PROCEDURE generate_redo_load()
BEGIN
    DECLARE i INT DEFAULT 0;
    WHILE i < 100 DO
        INSERT INTO test_rec_insert VALUES (1000 + i, CONCAT('User', i), i * 10.5);
        SET i = i + 1;
    END WHILE;
END;

CALL generate_redo_load();
DROP PROCEDURE generate_redo_load;

-- ============================================================================
-- Test 24: Rollback (UNDO application)
-- ============================================================================

CREATE TABLE test_rollback (
    id INT PRIMARY KEY,
    data VARCHAR(100)
) ENGINE=InnoDB;

START TRANSACTION;
INSERT INTO test_rollback VALUES (1, 'data1');
INSERT INTO test_rollback VALUES (2, 'data2');
ROLLBACK;  -- Undo records are used

START TRANSACTION;
INSERT INTO test_rollback VALUES (1, 'real_data1');
COMMIT;

START TRANSACTION;
UPDATE test_rollback SET data = 'modified' WHERE id = 1;
ROLLBACK;  -- Undo the update

-- ============================================================================
-- Test 25: Large Transaction
-- ============================================================================

CREATE TABLE test_large_trx (
    id INT PRIMARY KEY AUTO_INCREMENT,
    data VARCHAR(500)
) ENGINE=InnoDB;

-- Large transaction with many operations
START TRANSACTION;
INSERT INTO test_large_trx (data)
SELECT REPEAT(CHAR(65 + (i % 26)), 400) FROM
(SELECT 1 AS i UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20) t;
COMMIT;

-- ============================================================================
-- Cleanup and Summary
-- ============================================================================

SELECT 'Redo log test SQL execution completed!' AS Status;
SELECT 'Various redo log record types should now be present in redo logs' AS Info;
SELECT 'Check ib_logfile* or #innodb_redo/ directory' AS Location;

-- To examine redo logs, you can use:
-- 1. innochecksum utility
-- 2. MySQL Enterprise Backup mysqlbackup
-- 3. Your custom redo log parser

-- Note: Redo logs are binary files, not human-readable
-- Location (MySQL 8.0+): datadir/#innodb_redo/
-- Location (MySQL 5.7): datadir/ib_logfile0, ib_logfile1, etc.
